[language-server.jdtls]
command = "java"
args = [
  "-Declipse.application=org.eclipse.jdt.ls.core.id1",
  "-Dosgi.bundles.defaultStartLevel=4",
  "-Declipse.product=org.eclipse.jdt.ls.core.product",
  "-Dlog.level=ALL",
  "-noverify",
  "-Xmx1G",
  "-jar", "/home/zyoung/Code/XM/Linux/jdtls/plugins/org.eclipse.equinox.launcher_*.jar",
  "-configuration", "/home/zyoung/Code/XM/Linux/jdtls/config_linux",
  "-data",    "/home/zyoung/Code/XM/Linux/jdtls/workspace"
]

[[language]]
name = "java"
language-servers = ["jdtls"]

[language-server.ts]
command = "typescript-language-server"
args = ["--stdio"]

[[language]]
name = "javascript"
language-servers = ["ts"]

[[language]]
name = "typescript"
language-servers = ["ts"]

[[language]]
name = "python"
# language-servers = ["pyright"]
language-servers = ["pylsp", "ruff"]
formatter = { command = "ruff", args = ["format", "-"] }

[[language]]
name = "go"
language-servers = ["gopls"]
formatter = { command = "gofumpt" }
